# Generated by Django 4.2.5 on 2023-09-30 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='cattle_stock/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cattle', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.cattle')),
            ],
        ),
        migrations.CreateModel(
            name='Sheep_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='sheep_stock/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sheep', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.sheep')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('street', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_shipped', models.BooleanField(default=False)),
                ('cattle', models.ManyToManyField(blank=True, related_name='cattleorder+', to='store.cattle_stock')),
                ('sheep', models.ManyToManyField(blank=True, related_name='sheeporder+', to='store.sheep_stock')),
            ],
        ),
    ]
