# Generated by Django 4.2.5 on 2023-10-09 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_item_ordermodel_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle_stock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='sheep_stock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='store.category'),
        ),
    ]
