# Generated by Django 4.2.5 on 2023-10-10 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cattle_stock_price_remove_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, default='i', on_delete=django.db.models.deletion.CASCADE, related_name='item', to='store.category'),
        ),
    ]
