# Generated by Django 4.2.5 on 2023-10-11 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cattle',
            field=models.ForeignKey(blank=True, null=True,  on_delete=django.db.models.deletion.CASCADE, to='store.cattle_stock'),
        ),
        migrations.AddField(
            model_name='item',
            name='sheep',
            field=models.ForeignKey(blank=True, null=True,  on_delete=django.db.models.deletion.CASCADE, to='store.sheep_stock'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='menu_images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
