# Generated by Django 4.2.5 on 2023-10-10 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
