# Generated by Django 4.2.5 on 2023-10-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('closing_date', models.DateField(blank=True)),
                ('number_of_open_position', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
