# Generated by Django 4.2.5 on 2023-12-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_jobpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('details', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, upload_to='operations/')),
                ('image2', models.ImageField(upload_to='operations')),
            ],
        ),
    ]
