# Generated by Django 4.2.5 on 2023-12-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_farmoperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=800, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('resume', models.FileField(blank=True, upload_to='resumes/')),
                ('motivational_letter', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='farmoperation',
            name='image2',
            field=models.ImageField(upload_to='operations/'),
        ),
    ]
