# Generated by Django 4.2.5 on 2023-12-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_jobapplicant_alter_farmoperation_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmoperation',
            name='image2',
            field=models.ImageField(blank=True, upload_to='operations/'),
        ),
    ]
